---
- name: Test Kubernetes Core Collection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather cluster info
      kubernetes.core.k8s_cluster_info:
      register: api_status
      delegate_to: localhost
